### ISSUE TITLE
fix random spam triggering whenever ping spikes.

### ISSUE THREAD

**Issue by WindowsMeosu** [realMiloTilo/osu-meerkat#28]

**Comment by qwrmolly** [comment]
meerkatv2 also has this affect after testing the unfinished code in the private repository with all the IRC stuff (meerkata)
assuming because the automation is rebuilt off of meerkatv1's code. (ircv1)

**Comment by WindowsMeosu** [comment]
![image](https://user-images.githubusercontent.com/104236864/190933248-4978a76d-daf5-4b1f-9d2f-54105c7183df.png)
seems to work well, hopefully it goes as planned so it doesn't break whenever we merge realmilotilo/osu-meerkata and realmilotilo/osu-meerkat to become one.

**Comment by WindowsMeosu** [comment]
reopening this since we hadn't merged yet
